### ISSUE TITLE
Move to JuliaDiffEq

### ISSUE THREAD

**Issue by ViralBShah** [JuliaDiffEq/ODE.jl#112]
I suggest moving ODE.jl to JuliaMath unless we want to put all differential equations related packges in their own org.

**Comment by ViralBShah** [comment]
Given that Sundials.jl is already in JuliaMath, this makes sense.

**Comment by pwl** [comment]
I would rather have all the ODE related package in a single org, there are already at least five of such packages (ODE.jl, ODEInterface.jl, DifferentialEquations.jl, Sundials.jl and IVPTestSuite.jl) and ODE community is already big by itself.  This way we could have a single overview page of all the available solvers, we could work on a common API and test suites.

But moving ODE.jl to JuliaMath would be a good temporary measure before we have an org of our own set up.

**Comment by ChrisRackauckas** [comment]
I agree it makes sense. Though a more general DiffEq Org would make more sense to pull the general differential equations community together. Now that I have everything wrapped in DifferentialEquations.jl, making sure APIs are compatible in some sense is starting to matter more. But ODEs are the easy part. Making sure things are compatible with the PDE/FEM packages will be the next goal: Julia could benefit a lot if things like HP-FEM, JuliaFEM, etc. play nicely with the ODE packages (indeed, that was the whole reason for rolling the ODE part of DifferentialEquations.jl in the first place).

**Comment by ViralBShah** [comment]
Why not just create the org right away?

**Comment by ViralBShah** [comment]
Cc @tkelman @simonbyrne

**Comment by pwl** [comment]
There is already https://github.com/JuliaODE, where we are working on the next iteration of ODE.jl.

**Comment by ViralBShah** [comment]
Can we move Sundials.jl and ODE.jl there? I guess if you add me to that org, I can do the move.

**Comment by ViralBShah** [comment]
Perhaps rename it to be able to accommodate other PDE and FEM stuff as well - or would you rather keep it ODE focussed?

**Comment by pwl** [comment]
Isn't it the problem that there already is a fork of ODE.jl in there?

**Comment by pwl** [comment]
@mauro3 what do you think about it?

**Comment by ViralBShah** [comment]
Can we get rid of the fork?

**Comment by ChrisRackauckas** [comment]
Naming it for ODEs is fairly restrictive to the scope. Most non-trivial uses of ODE solvers are likely for DDEs, PDEs, SPDEs, etc., so I think it's wrong to separate them from their standard use cases.

**Comment by pwl** [comment]
DifferentialEquations would be a perfect name for the org, but it's already taken.

**Comment by ChrisRackauckas** [comment]
I think as @ViralBShah suggested JuliaDiffEq is good. DiffEq is a pretty well accepted shorthand for Differential Equations.

**Comment by pwl** [comment]
@ChrisRackauckas sounds good to me.

@ViralBShah, this fork is under a heavy development right now, we should be able to merge it back to ODE.jl soonish (maybe in a matter of weeks).  I could, in principle move it back to my account though.

**Comment by ViralBShah** [comment]
Well, if we are going to create a new JuliaDiffEq organization, then this problem will not occur.

**Comment by ChrisRackauckas** [comment]
Yes, the ODE.jl fork is a much more developed version of ODE.jl. In fact, it's the version that I wrapped into DifferentialEquations.jl for that reason. If anything, something based around that fork should be what the "new ODE.jl" is (once it polishes some rough edges).

**Comment by pwl** [comment]
@ViralBShah I think creating a new org is the best option, once we merge our fork to we could simply get rid of JuliaODE.

**Comment by ViralBShah** [comment]
Is someone here creating the new org? Or would you guys rather I do it?

**Comment by ChrisRackauckas** [comment]
I can do it.

**Comment by pwl** [comment]
@ChrisRackauckas go for it

**Comment by mauro3** [comment]
Oh no, now we have to create a logo! ;-)

**Comment by ChrisRackauckas** [comment]
Who else should I invite? I did @ViralBShah, @pwl and @mauro3. Moving ODE.jl is first priority to get it off JuliaLang for testing. @luchr should be in on this since ODEInterface. Should Sundials move once more?

(What's the procedure for moving? Just point all of the URLs in METADATA to the new location?)

**Comment by tkelman** [comment]
> Just point all of the URLs in METADATA to the new location?

Yes but you actually don't even need to do this right away, github will put in place an automatic redirect if an admin in both orgs does "transfer ownership" under the settings. Updating the metadata url is a cleanup thing that should be done eventually but nothing will break right away if you don't.

**Comment by simonbyrne** [comment]
Can also rename JuliaODE.

**Comment by tkelman** [comment]
Looks like Viral took care of it, close?

**Comment by ViralBShah** [comment]
Have also moved Sundials to JuliaDiffEq.

**Comment by tkelman** [comment]
Makes sense. I'm somehow the top committer on Sundials despite never using it, could someone invite me here?

**Comment by mauro3** [comment]
Invite @acroy
