### ISSUE TITLE
StackOverflow from depreciation warnings

### ISSUE THREAD

**Issue by rlecover007** [JuliaDiffEq/ODE.jl#116]
When using ODE23, 45, or 78, Julia crashes from receiving too many "WARNING: [a] concatenation is deprecated; use collect(a) instead
 in depwarn at deprecated.jl:73
 in oldstyle_vcat_warning at ./abstractarray.jl:29
 in oderk_adapt at /home/rachel/.julia/v0.4/ODE/src/runge_kutta.jl:220 (repeats 36 times)
while loading no file, in expression starting on line 0"

**Comment by mauro3** [comment]
Is this on Julia 0.5? Can you post your test case?  Running a simple ode does not produce any warnings:
```
  _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-pc-linux-gnu

julia> using ODE

julia> t,y=ode78((t,y)->6.0, 0., [0:.1:1;])
([0.0,0.0001,0.1,0.2,0.3,0.4,0.4001,0.5,0.6,0.7,0.8,0.8001,0.9,1.0],[0.0,0.0006,0.6,1.2,1.8,2.4,2.4006,3.0,3.6,4.2,4.8,4.8006,5.4,6.0])
```
Also what is the output of `Pkg.status("ODE")`?

Last, deprecation warnings should not crash julia, so if you get a small test-case, file an issue there too.

**Comment by stevengj** [comment]
I'm guessing that @rlecover007 is using the deprecated syntax in his own code (the function passed to `odeXX`).

**Comment by ChrisRackauckas** [comment]
>Is this on Julia 0.5?

From his warning you see it's Julia v0.4, but that shouldn't matter because the tests still pass on v0.4.

**Comment by mauro3** [comment]
As we didn't get anymore feedback, I'll close it. @rlecover007, please open again if you feel this hasn't been resolved.
