### ISSUE TITLE
ODE45 does not return Array-valued solutions to requested accuracy

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaDiffEq/ODE.jl#118]
Consider the IVP `y' = y` with `y(0) = 1`. Since we know `y(1) = e`, let's check `ode45`:
```julia
julia> using ODE

julia> t, y = ode45((t, y) -> y, 1.0, 0:0.1:1; reltol=eps(), abstol=0.0)
([0.0,0.000294638,0.00149288,0.00398769,0.00644932,0.00891086,0.0113735,0.0138347,0.0162958,0.0187545  …  0.978783,0.981241,0.983702,0.986162,0.988625,0.991086,0.993549,0.996013,0.998472,1.0],[1.0,1.00029,1.00149,1.004,1.00647,1.00895,1.01144,1.01393,1.01643,1.01893  …  2.66122,2.66777,2.67434,2.68093,2.68754,2.69416,2.7008,2.70747,2.71413,2.71828])

julia> y[end]-e
-2.220446049250313e-15

```

Now, the accuracy isn't exactly machine epsilon, but close enough for jazz. What if we try the same calculation with an array-valued initial value?
```julia
julia> t, y = ode45((t, y) -> y, [1.0], 0:0.1:1; reltol=eps(), abstol=0.0)
([0.0,4.54279e-6,8.61664e-6,1.25171e-5,1.63502e-5,2.01568e-5,2.39527e-5,2.77444e-5,3.15345e-5,3.53238e-5  …  0.999969,0.999973,0.999976,0.99998,0.999984,0.999988,0.999991,0.999995,0.999999,1.0],Array{Float64,1}[[1.0],[1.0],[1.00001],[1.00001],[1.00002],[1.00002],[1.00002],[1.00003],[1.00003],[1.00004]  …  [2.7182],[2.71821],[2.71822],[2.71823],[2.71824],[2.71825],[2.71826],[2.71827],[2.71828],[2.71828]])

julia> y[end]-e
1-element Array{Float64,1}:
 6.36934e-10

```
Nothing else has changed, but it's nowhere near the relative accuracy requested. Presumably this is an issue for higher dimensional array-valued IVPs as well. (This was uncovered due to the exploration of nontrivial periodic orbits of electrons round nuclei by @JFlry and @trefethen in [chebfun](http://www.chebfun.org/examples/ode-nonlin/TwoElectrons.html).)

**Comment by MikaelSlevinsky** [comment]
Oops, my fault. I should have used the syntax:
```julia
julia> using ODE

julia> t, y = ode45((t, y) -> [y[1]], [1.0], 0:0.1:1; reltol=eps(), abstol=0.0)
([0.0,0.000294638,0.00149288,0.00398769,0.00644932,0.00891086,0.0113735,0.0138347,0.0162958,0.0187545  …  0.978783,0.981241,0.983702,0.986162,0.988625,0.991086,0.993549,0.996013,0.998472,1.0],Array{Float64,1}[[1.0],[1.00029],[1.00149],[1.004],[1.00647],[1.00895],[1.01144],[1.01393],[1.01643],[1.01893]  …  [2.66122],[2.66777],[2.67434],[2.68093],[2.68754],[2.69416],[2.7008],[2.70747],[2.71413],[2.71828]])

julia> y[end]-e
1-element Array{Float64,1}:
 -2.22045e-15
```

**Comment by MikaelSlevinsky** [comment]
But it's still kind of strange, because the return types of `(t, y) -> y` and `(t, y) -> [y[1]]` are both vectors for a vector input in `y`, so both uses of `ode45` should be equivalent.

**Comment by ChrisRackauckas** [comment]
The first one returns a reference to the same vector, while the other is a new vector vector with the same values. This is very different. The first way would make all intermediate steps coupled, and I am surprised that would work at all.

**Comment by MikaelSlevinsky** [comment]
Oh I see, thanks.

**Comment by MikaelSlevinsky** [comment]
Does this mean that most temporary allocations in `ODE` solvers could be trivially removed if the flow were specified as a function that modifies a temporary variable, such as `(t, y, ytemp) -> (ytemp[1] = y[1]; ytemp)` in the above? A tableau of temporary variables, the size of the RK method, could be initialized and calculating an internal stage would amount to updating the temporary variable with a call `f!(t, y, internal_stage_temp[i,j])`.

**Comment by ChrisRackauckas** [comment]
Yes, this is how other ODE solvers like those in DifferentialEquations.jl (OrdinaryDiffEq.jl) do it.

**Comment by MikaelSlevinsky** [comment]
Great, thanks!
