### ISSUE TITLE
Integrate the dassl DAE solver from DASSL.jl

### ISSUE THREAD

**Issue by ivarne** [JuliaDiffEq/ODE.jl#36]
See:
- https://github.com/pwl/DASSL.jl
- https://groups.google.com/forum/m/#!topic/julia-users/egfvEo-4hP8

This might be a good excuse to continue the discussion on efficient ways to use different problem specifications in a consistent way.

@pwl

**Comment by ChrisRackauckas** [comment]
Closing this because it's been completed by the organization layout and the common interface(s).
