### ISSUE TITLE
Solver for implicit ODE:s

### ISSUE THREAD

**Issue by tlycken** [JuliaDiffEq/ODE.jl#5]
I need one =)

If I can find a good algorithm somewhere, I'll try to implement one, but in the meantime I'm putting it out there if someone else happens to be sitting on one.

**Comment by ufechner7** [comment]
Any progress on this issue?

**Comment by ChrisRackauckas** [comment]
There's DASSL and Sundials. Sundials is also available through the common `solve` interface.

**Comment by mauro3** [comment]
There is https://github.com/mobius-eng/RadauBVP.jl

**Comment by ufechner7** [comment]
I try to convert the following Python code:
https://gist.github.com/ufechner7/8b98b6983cf2b084cf93a6b46e03d92c
Can RadauBVP be used to solve an implicit problem?

**Comment by ChrisRackauckas** [comment]
I'm not sure, and RadauBVP is definitely under a good amount of development and doesn't have common usability features like choice of tolerances yet. That's why I'd suggest Sundials if your problem is on Float64's: it's pretty highly regarded as one of the best solvers, even not in Julia (for example, it's the basis of a lot of methods in PETSc).

```julia
const G_EARTH  = [0.0, 0.0, -9.81] # gravitational acceleration
function res1(t, y, yd,out)
    res[1] = y[3:6]  - yd[0:3]
    res[2] = yd[3:6] - G_EARTH 
end
```

Then you can use `idasol`

```julia
function idasol(f::Function, y0::Vector{Float64}, yp0::Vector{Float64}, t::Vector{Float64}, userdata::Any=nothing;
                reltol::Float64=1e-3, abstol::Float64=1e-6, diffstates::Union{Vector{Bool},Void}=nothing)
```

This will be easier (and more modular) when the common solve interface is ready for DAEs, but currently that's not the case.

**Comment by ufechner7** [comment]
My experiance with Radau (via Assimulo) is better then with IDA, but I will try IDA. Can I provide user defined Jacobians to IDA?

**Comment by ChrisRackauckas** [comment]
>Can I provide user defined Jacobians to IDA?

I am pretty sure there's a way to, but maybe not in the Sundials.jl simplified interface.

I have noted the same differences between the Hairer Radau and BDF based methods before (in Julia, see the [stiff benchmarks at DiffEqBenchmarks.jl](https://github.com/JuliaDiffEq/DiffEqBenchmarks.jl)). That said, the Hairer algorithms are really well known as really good implementations so I don't think that their efficiency automatically transfers over to the new RadauBVP.jl (though it's hard to know, it could. I don't have it in the DiffEq common interface yet to benchmark it against the others). If you need the Hairer algorithms (i.e. your implicit-ness is in a mass matrix form) you can check out ODEInterface.jl 

Note that simple benchmarks will not highlight the advantage of multistep-based schemes like IDA which only comes through when the function call `f` is relatively expensive. If that's the case with your problem you'd likely be better off with IDA.

**Comment by ChrisRackauckas** [comment]
Closing this because there is DASSL.jl for a native Julia method, and Sundials.jl and DASRK.jl for wrappers to popular FORTRAN/C codes. Future requests should now be more specific/actionable since we know have these options.
